#!/bin/sh

USER_NAME=${NAME:-"Jocelino Neto"}
USER_EMAIL=${EMAIL:-"netoj96@live.com"}
CURRENT_DIR="$(dirname "$0")"

git config --global user.name "$USER_NAME"
git config --global user.email "$USER_EMAIL"
git config --global core.excludesfile ""$CURRENT_DIR"/.gitignore"
