#!/usr/bin/env bash
# Synchronize visu-uat local with remotes.
#
# Merge branch when set

set -eu 


#
# Utilitários
#

C_BOLD=1
C_H1='1;32'
C_H2='1;34'
C_H3='1;36'
C_ERROR='97;41'
C_WARN='30;43'


color () {
    printf '\033[%sm%s\033[0m' "$1" "$2"
}

echoH1 () {
    echo "$(color "$C_H1" '==>') $(color "$C_BOLD" "$1")"
}

echoH2 () {
    echo "  $(color "$C_H2" '->') $(color "$C_BOLD" "$1")"
}

echoH3 () {
    echo "  $(color "$C_H3" '~>') $(color "$C_BOLD" "$1")"
}

error () {
    >&2 echo "$(color "$C_ERROR" ' ERROR ') $2"
    exit "$1"
}

warn () {
    >&2 echo "$(color "$C_WARN" ' WARN ') $1"
    sleep 1
}


DEFAULT_BRANCH=visu

BASE_BRANCH=${ROOT_BRANCH:-$DEFAULT_BRANCH}


echoH1 'Alterando para branch principal'
git checkout "$BASE_BRANCH"


## Sincronizar o remoto com local
echoH2 'Requisitando modificações da branch remota'
echoH3 'git pl uat'
git pull uat master:$(git rev-parse --abbrev-ref HEAD)
echoH3 'git pl uat-subapp'
git pull uat-subapp master:$(git rev-parse --abbrev-ref HEAD)



## Jutnar ramificação base com alterações
if [ $# -gt 0 ]; then
    while [ $# -gt 0 ];
    do
        echoH2 'Juntando ramificação '$1'.'
        git merge --ff "$1"
    done
else
    warn 'Nenhuma ramificação deverá ser juntada.'
fi;


