#!/usr/bin/env bash

# list all directories and fetch when exists `.git`

function danger () {
    echo -e "\033[0;101m\033[30m$1\033[0m"
}

function iterate_directory () {
    for D in $(find $1 -mindepth 1 -maxdepth 1 -type d); do
        check_has_git "$(realpath "${D}")"
    done
}


function check_has_git () {
    
    if [[ ! -d "$1" ]]; then
        danger  "$(realpath "$1") não é um diretório válido"
        return;
    fi

    cd "$1"

    
    if [[ -d ".git" ]]; then
        echo -e "\033[0;102m\033[30m   [FETCH]  \033[0m |  $1"
        git fetch --all --prune
    else
        iterate_directory "$1"
    fi

    cd ".."
}

iterate_directory "$(pwd)"
