#!/bin/sh


# sudo -k

throws () {
    echo -e "\033[41;97m"$1"\033[0m"
}

info () {
    echo -e "\033[40;1;43m"$1"\033[0m"
}


if [[ $# -gt 0 ]]; then
    if [[ $1 = 'install'  ]] || [[ $1 = 'i' ]]; then
        if [[ $# -gt 1 ]]; then
            sudo dnf install -y "$2"
        else
            throws "Install software name's required"
            exit 1
        fi
    elif [[ $1 = 'update' ]] || [[ $1 = 'u' ]]; then

        info "\n\nAuto remove, check updates and upgrade\n"
        sudo dnf autoremove
        sudo dnf check-update
        sudo dnf upgrade --refresh --best --allowerasing --skip-broken
        sudo dnf update

        sudo flatpak update

        info "\n\nFlatpak packages\n"
        flatpak --columns=name,size list
        echo -e "\n\n"

        flatpak uninstall --unused

        info "\n\nkernels:\n"
        rpm -qa kernel
        info "\n\ndnf remove kernel-??\n"

    elif [[ $1 = 'battery' ]] || [[ $1 = 'b' ]]; then
    while [[ true ]]; do
        clear
        echo "Situação de bateria em $(date)"
        echo "$((upower -i $(upower -e | grep battery_)) | grep -E 'capacity|state|percentage|temperature')"
        sleep 4
    done
    fi
else
    throws "Opção inválida"
    exit 1
fi

