#!/bin/sh


# sudo -k

throws () {
    echo -e "\033[41;97m"$1"\033[0m"
    
    notify-send --urgency=critical -i error "An error occours" "$1"
}

info () {
    echo -e "\033[40;1;43m"$1"\033[0m"
}

check_if_sudo () {
    if [[ "$EUID" -ne 0 ]]; then
        notify-send --urgency=normal -i info "Info" "$1"
        sudo echo ""
    fi
}

check_if_sudo "Sudo required"


# php 74
# sudo dnf install php74-php-cli php74-php-fpm php74-php-gd php74-php-curl php74-php-mysqlnd php74-php-zip php74-php-xml php74-php-mbstring php74-php-bcmath php74-php-sodium
# php 55
# sudo dnf install php5-php-cli php5-php-fpm php5-php-gd php5-php-curl php5-php-mysqlnd php5-php-zip php5-php-xml php5-php-mbstring php5-php-bcmath php5-php-sodium


if [[ $# -gt 0 ]]; then
    if [[ $1 = 'install'  ]] || [[ $1 = 'i' ]]; then
        if [[ $# -gt 1 ]]; then
            sudo dnf install -y "$2"
        else
            throws "Install software name's required"
            exit 1
        fi
    elif [[ $1 = 'update' ]] || [[ $1 = 'u' ]]; then

        info "\n\nAuto remove, check updates and upgrade\n"
        sudo dnf autoremove
        sudo dnf check-update
        sudo dnf upgrade --refresh --best --allowerasing --skip-broken
        sudo dnf update

        sudo flatpak update

        info "\n\nFlatpak packages\n"
        flatpak --columns=name,size list
        echo -e "\n\n"

        flatpak uninstall --unused

        info "\n\nkernels:\n"
        rpm -qa kernel
        info "\n\ndnf remove kernel-??\n"

    elif [[ $1 = 'battery' ]] || [[ $1 = 'b' ]]; then
    while [[ true ]]; do
        clear
        echo "Situação de bateria em $(date)"
        echo "$((upower -i $(upower -e | grep battery_)) | grep -E 'capacity|state|percentage|temperature')"
        sleep 4
    done
    fi
else
    throws "Opção inválida"
    exit 1
fi

