#!/bin/sh


# sudo -k

throws () {
    echo -e "\033[41;97m"$1"\033[0m"
}

info () {
    echo -e "\033[40;1;43m"$1"\033[0m"
}


if [[ $# -gt 0 ]]; then
    if [[ $1 = 'install'  ]] || [[ $1 = 'i' ]]; then
        if [[ $# -gt 1 ]]; then
            sudo dnf install -y "$2"
        else
            echo "Install software name's required"
            exit 1
        fi
    elif [[ $1 = 'update' ]] || [[ $1 = 'u' ]]; then

        sudo dnf autoremove
        sudo dnf check-update
        sudo dnf upgrade --refresh

        sudo flatpak update

        echo -e "\n\n\nFlatpak packages"
        flatpak --columns=name,size list
        echo -e "\n\n"

        flatpak uninstall --unused

        echo -e "\n\nkernels: "
        rpm -qa kernel
        echo -e "dnf remove kernel-??"

    fi
fi

